/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package organizadordetarefas;

import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author gabri
 */
public class Frame extends javax.swing.JFrame {

    public static ArrayList<javax.swing.JTextField> labels = new ArrayList<javax.swing.JTextField>();
    public static ArrayList<javax.swing.JButton> buttons = new ArrayList<>();

    public static ArrayList<JTextField> getLabels() {
        return labels;
    }

    public ArrayList<JButton> getButtons() {
        return buttons;
    }
    
    public Frame() {
        initComponents();
        setLocationRelativeTo(null);
        setLayout(null);
        jPanel1.setLayout(null);
        setResizable(false);
        adicionarInicio();
        defInit(subirBtn);
        defInit(descerBtn);
    }
    
    
    public void defInit(JButton j){
        j.setOpaque(false);
        j.setContentAreaFilled(false);
        j.setBorderPainted(false);
        j.setCursor(new Cursor(Cursor.HAND_CURSOR));
        j.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t1 = new javax.swing.JTextField();
        x1 = new javax.swing.JButton();
        t2 = new javax.swing.JTextField();
        x2 = new javax.swing.JButton();
        t3 = new javax.swing.JTextField();
        x3 = new javax.swing.JButton();
        x4 = new javax.swing.JButton();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        x5 = new javax.swing.JButton();
        x6 = new javax.swing.JButton();
        t6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AdicionarBtn = new javax.swing.JButton();
        adicionar = new javax.swing.JTextField();
        subirBtn = new javax.swing.JButton();
        descerBtn = new javax.swing.JButton();

        t1.setText("INFORMAÇÕES TAREFA 1");
        t1.setLocation(32, 1);

        x1.setText("X");

        t2.setText("INFORMAÇÕES TAREFA 2");

        x2.setText("X");

        t3.setText("INFORMAÇÕES TAREFA 3");
        t1.setLocation(32, 1);

        x3.setText("X");

        x4.setText("X");

        t4.setText("INFORMAÇÕES TAREFA 4");

        t5.setText("INFORMAÇÕES TAREFA 5");
        t1.setLocation(32, 1);

        x5.setText("X");

        x6.setText("X");

        t6.setText("INFORMAÇÕES TAREFA 6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        setSize(new java.awt.Dimension(550, 200));

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jPanel1.setAutoscrolls(true);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Tarefas");

        jLabel2.setText("Clique na tarefa para expandir suas informações");

        AdicionarBtn.setText("Adicionar");
        AdicionarBtn.setOpaque(false);
        AdicionarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarBtnActionPerformed(evt);
            }
        });

        subirBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/organizadordetarefas/arrowUp.png"))); // NOI18N
        subirBtn.setOpaque(false);
        subirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirBtnActionPerformed(evt);
            }
        });

        descerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/organizadordetarefas/arrowDown.png"))); // NOI18N
        descerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(descerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(AdicionarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                        .addComponent(subirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(AdicionarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(subirBtn)))
                .addGap(317, 317, 317)
                .addComponent(descerBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(481, 481, 481))
        );

        jScrollPane1.setViewportView(jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descerBtnActionPerformed
        organizadorDeTarefas.setIndexAtual(organizadorDeTarefas.getIndexAtual()+1);
        if(6 + organizadorDeTarefas.getIndexAtual() == labels.size())
            descerBtn.setEnabled(false);
        subirBtn.setEnabled(true);

        organizadorDeTarefas.reposicionar(organizadorDeTarefas.indexAtual);
    }//GEN-LAST:event_descerBtnActionPerformed

    private void subirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirBtnActionPerformed
        organizadorDeTarefas.setIndexAtual(organizadorDeTarefas.getIndexAtual()-1);
        if(organizadorDeTarefas.getIndexAtual() == 0)
            subirBtn.setEnabled(false);
        descerBtn.setEnabled(true);

        organizadorDeTarefas.reposicionar(organizadorDeTarefas.indexAtual);
    }//GEN-LAST:event_subirBtnActionPerformed

    public void adicionarInicio(){
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            arquivo.salvarArquivo();
        }, "Shutdown-thread"));
        ArrayList<String> salvar = new ArrayList<>();
        salvar = arquivo.carregarArquivo();
        if(salvar == null)
            return;
        
        for(String lin: salvar){
            labels.add(new javax.swing.JTextField(lin));
            buttons.add(new javax.swing.JButton("X"));
            jPanel1.add(labels.get(labels.size()-1));
            jPanel1.add(buttons.get(buttons.size()-1));
            buttons.get(buttons.size()-1).setCursor(new Cursor(Cursor.HAND_CURSOR));
            organizadorDeTarefas.setUpListeners();
        }
        organizadorDeTarefas.reposicionar(0);
        
    }
    
    
    private void AdicionarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarBtnActionPerformed

        labels.add(new javax.swing.JTextField(adicionar.getText()));
        buttons.add(new javax.swing.JButton("X"));
        adicionar.setText("");
        jPanel1.add(labels.get(labels.size()-1));
        jPanel1.add(buttons.get(buttons.size()-1));
        buttons.get(buttons.size()-1).setCursor(new Cursor(Cursor.HAND_CURSOR));
        if(labels.size()>6)
            descerBtn.setEnabled(true);  
        organizadorDeTarefas.setUpListeners();
        organizadorDeTarefas.reposicionar(0);
    }//GEN-LAST:event_AdicionarBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }
    public void removerCompletamente(JButton a){
        remove(a);
    }
    public void removerCompletamente(JTextField a){
        remove(a);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarBtn;
    private javax.swing.JTextField adicionar;
    private javax.swing.JButton descerBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton subirBtn;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JButton x1;
    private javax.swing.JButton x2;
    private javax.swing.JButton x3;
    private javax.swing.JButton x4;
    private javax.swing.JButton x5;
    private javax.swing.JButton x6;
    // End of variables declaration//GEN-END:variables
}
